# Generated by Django 3.1.7 on 2021-03-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('on1', models.IntegerField()),
            ],
        ),
    ]
