# Generated by Django 3.1.7 on 2021-03-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0004_auto_20210327_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on1', models.IntegerField(default=0)),
                ('on2', models.IntegerField(default=0)),
                ('on3', models.IntegerField(default=0)),
                ('on4', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='creatpoll',
            name='on1',
        ),
        migrations.RemoveField(
            model_name='creatpoll',
            name='on2',
        ),
        migrations.RemoveField(
            model_name='creatpoll',
            name='on3',
        ),
        migrations.RemoveField(
            model_name='creatpoll',
            name='on4',
        ),
    ]
