# Generated by Django 3.1.7 on 2021-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0005_auto_20210327_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.AddField(
            model_name='creatpoll',
            name='four_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatpoll',
            name='on1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatpoll',
            name='on2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatpoll',
            name='on3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatpoll',
            name='on4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatpoll',
            name='one_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatpoll',
            name='three_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatpoll',
            name='two_1',
            field=models.IntegerField(default=0),
        ),
    ]
