# Generated by Django 3.1.7 on 2021-03-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0006_auto_20210327_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('o1', models.CharField(max_length=50)),
                ('o2', models.CharField(max_length=50)),
                ('o3', models.CharField(max_length=50)),
                ('o4', models.CharField(max_length=50)),
                ('on1', models.IntegerField(default=0)),
                ('on2', models.IntegerField(default=0)),
                ('on3', models.IntegerField(default=0)),
                ('on4', models.IntegerField(default=0)),
            ],
        ),
    ]
