# Generated by Django 3.1.7 on 2021-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0007_openpoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatpoll',
            name='email',
            field=models.IntegerField(default=0),
        ),
    ]
