# Generated by Django 3.1.7 on 2021-03-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0008_creatpoll_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatpoll',
            name='email',
        ),
    ]
