# Generated by Django 3.1.7 on 2021-03-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0009_remove_creatpoll_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatpoll',
            name='o1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='creatpoll',
            name='o2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='creatpoll',
            name='o3',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='creatpoll',
            name='o4',
            field=models.CharField(max_length=150),
        ),
    ]
