# Generated by Django 3.1.7 on 2021-04-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0012_creatpoll_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openpoll',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='openpoll',
            name='o1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='openpoll',
            name='o2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='openpoll',
            name='o3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='openpoll',
            name='o4',
            field=models.TextField(),
        ),
    ]
